# Rust MakeFile
# 
# github: https://github.com/sagiegurari/cargo-make
# 
# install: cargo install cargo-make
# 
# menu: cargo make list
# run task: cargo make android-build

[env]
APPS = "apps"             # 后端应用目录
MOBILE = "apps/mobile"    # 移动端应用
MOBILE_WEB = "mobile-web" # 移动前端项目
# NDK_HOME = "/home/user/.Android/Sdk/ndk/28.0.12433566" # Android NDK HOME, 支持直接读取系统环境变量
# TAURI_BUNDLER_WIX_FIPS_COMPLIANT = "true" # 如果您的系统要求 MSI 软件包符合 FIPS 标准，则设置此环境变量。


# ============= 功能列表 =============
[tasks.list]
description = "List all tasks."
category = "menu"
script = [
    "cargo make --quiet --list-category-steps deps",
    "cargo make --quiet --list-category-steps build",
    "cargo make --quiet --list-category-steps utils",
]


# ============= 安装依赖 =============
[tasks.install-java-sdk-deps]
private = true
description = "Install java sdk deps."
category = "deps"
command = "sudo"
args = ["pacman", "-S", "--needed", "jdk17-openjdk"]

[tasks.install-linux-sys-deps]
private = true
description = "Install linux sys deps."
category = "deps"
command = "sudo"
args = [
    "pacman",
    "-S",
    "--needed",
    "binutils",
    "gcc",
    "lld",       # 链接器
    "llvm",      # 链接器
    "xdg-utils",
]

[tasks.install-linux-aur-sys-deps]
private = true
description = "Install linux aur sys deps."
category = "deps"
command = "yay"
args = [
    "-S",
    "--needed",
    "linuxdeploy", # build: linuxdeploy --appdir ./debox-pro-tools-gui.AppDir --output appimage
]

[tasks.install-linux-desktop-deps]
private = true
description = "Install linux desktop deps."
category = "deps"
command = "sudo"
args = [
    "pacman",
    "-S",
    "--needed",
    "webkit2gtk-4.1",
    "base-devel",
    "curl",
    "wget",
    "file",
    "openssl",
    "appmenu-gtk-module",
    "libappindicator-gtk3",
    "librsvg",
    "xdotool",
]

[tasks.install-win-nsis-deps]
private = true
description = "Install win nsis deps."
category = "deps"
command = "yay"
args = [
    "-S",
    "--needed",
    "nsis",     # 交叉编译为 Windows Nsis 包
]


[tasks.install-linux-appimage-deps]
private = true
description = "Install linux appimage deps."
category = "deps"
command = "sudo"
args = [
    "pacman",
    "-S",
    "--needed",
    "fuse",     # 运行 Linux AppImage
]


[tasks.install-cargo-deps]
private = true
description = "Install cargo deps."
category = "deps"
command = "cargo"
args = [
    "install",
    "cargo-xwin",       # Windows SDK
    "create-tauri-app", # 创建 Tauri 项目
    "tauri-cli",        # Tauri Cli 工具
    "sea-orm-cli",      # Sea-Orm Cli 工具
]

[tasks.install-rustup-linux-deps]
private = true
description = "Install rustup add linux deps."
category = "deps"
command = "rustup"
args = [
    "target",
    "add",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    # "x86_64-pc-windows-msvc",
]

[tasks.install-rustup-android-deps]
private = true
description = "Install rustup add android deps."
category = "deps"
command = "rustup"
args = [
    "target",
    "add",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",
]

[tasks.install-rustup-ios-deps]
private = true
description = "Install rustup add ios deps."
category = "deps"
command = "rustup"
args = [
    "target",
    "add",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",
]

# 初始化前端环境
[tasks.install-mobile-web]
description = "Init mobile-web."
category = "deps"
cwd = "${MOBILE_WEB}"
command = "pnpm"
args = ["install"]


[tasks.install]
description = "Init all deps."
category = "deps"
run_task = [
    { name = [
        "install-linux-sys-deps",
        # "install-linux-aur-sys-deps",
        "install-linux-desktop-deps",
        "install-win-nsis-deps",
        "install-linux-appimage-deps",
        "install-cargo-deps",
        "install-rustup-linux-deps",
        "install-rustup-android-deps",
        # "install-rustup-ios-deps",
        "install-mobile-web",
    ] },
]

# ============= 工具 =============
[tasks.clean-cargo]
description = "Clean cargo build"
category = "utils"
cwd = "${APPS}"
command = "cargo"
args = ["clean"]

[tasks.clean-android]
description = "Clean android build"
category = "utils"
cwd = "${MOBILE}/gen/android/app/"
command = "rm"
args = ["-rf", "build"]


[tasks.fmt]
description = "Cargo fmt all"
category = "utils"
cwd = "${APPS}"
command = "cargo"
args = ["fmt", "--all"]

# ============= 开发调式 =============
[tasks.dev]
description = "Build desktop dev."
category = "build"
cwd = "${MOBILE}"
command = "cargo"
args = ["tauri", "dev"]

[tasks.android-dev]
description = "Build android dev."
category = "build"
# env = { "CC_aarch64_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang", "CC_armv7_linux_androideabi" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang", "CC_x86_64_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang", "CC_i686_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android35-clang" }
cwd = "${MOBILE}"
command = "cargo"
args = ["tauri", "android", "dev"]

# ============= 打包 =============
[tasks.build]
description = "Build desktop build."
category = "build"
cwd = "${MOBILE}"
# NO_STRIP=true cargo tauri build
env = { "NO_STRIP" = true }
command = "cargo"
args = ["tauri", "build"]


[tasks.android-build]
description = "Build android build."
category = "build"
# env = { "CC_aarch64_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang", "CC_armv7_linux_androideabi" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang", "CC_x86_64_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang", "CC_i686_linux_android" = "${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android35-clang" }
cwd = "${MOBILE}"
command = "cargo"
args = ["tauri", "android", "build"]

[tasks.windows-build]
description = "Build windows build."
category = "build"
cwd = "${MOBILE}"
command = "cargo"
args = ["tauri", "build", "--target", "x86_64-pc-windows-gnu"]
