[package]
name = "err_code"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
color-eyre = { workspace = true }
serde = { workspace = true, features = ["derive"] }
