[package]
name = "axum_response"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
axum = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
