# 系统环境
env:
  env: "dev" # prod/test/dev

# 系统服务
server:
  base: # 系统服务地址配置
    address: "127.0.0.1" # 服务地址
    port: 8000 # 服务端口
  captcha: # 验证码
    expire: 120 # 验证码过期时间/s, 0-255
  upload: # 上传路径配置
    filepath: "./upload" # 上传文件路径


# PostgreSQL 数据库配置
postgresql:
  type: "postgresql" # 数据库类型
  key: "db" # db信息唯一标识
  host: "127.0.0.1" # IP或域名
  port: 5432 # 端口
  username: "one" # 账号
  password: "pass" # 密码
  db_name: "axum_admin_web" # 数据库名称
  schema: "public"
  options: # 参数配置
    max_connections: 100 # 设置池的最大连接数
    min_connections: 5 # 设置池的最小连接数
    connect_timeout: 10 # 设置获取连接时的超时持续时间
    acquire_timeout: 10 # 设置等待获取连接所花费的最大时间
    idle_timeout: 10 # 在关闭连接之前设置空闲持续时间
    max_lifetime: 10 # 设置单个连接的最大使用寿命
    logging_enable: true # 启用日志记录
    logging_level: "debug" # 日志记录级别（默认error）off/trace/debug/info/warn/error

# MySQL 数据库配置(示例)
mysql:
  type: "mysql" # 数据库类型
  key: "db" # db信息唯一标识
  host: "127.0.0.1" # IP或域名
  port: 3306 # 端口
  username: "one" # 账号
  password: "pass" # 密码
  db_name: "axum_admin_web" # 数据库名称
  options: # 参数配置
    max_connections: 5 # 设置池的最大连接数
    min_connections: 5 # 设置池的最小连接数
    connect_timeout: 10 # 设置获取连接时的超时持续时间
    acquire_timeout: 10 # 设置等待获取连接所花费的最大时间
    idle_timeout: 10 # 在关闭连接之前设置空闲持续时间
    max_lifetime: 10 # 设置单个连接的最大使用寿命
    logging_enable: false # 启用日志记录
    logging_level: "warn" # 日志记录级别（默认error）off/trace/debug/info/warn/error

# Sqlite3 数据库配置(示例)
sqlite:
  type: "sqlite" # 数据库类型
  key: "db" # db信息唯一标识
  sqlite_path: "sqlite://../mobile/data.dat?mode=rwc" # sqlite 路径
  options: # 参数配置
    max_connections: 100 # 设置池的最大连接数
    min_connections: 5 # 设置池的最小连接数
    connect_timeout: 10 # 设置获取连接时的超时持续时间
    acquire_timeout: 10 # 设置等待获取连接所花费的最大时间
    idle_timeout: 10 # 在关闭连接之前设置空闲持续时间
    max_lifetime: 10 # 设置单个连接的最大使用寿命
    logging_enable: false # 启用日志记录
    logging_level: "warn" # 日志记录级别（默认error）off/trace/debug/info/warn/error

# 日志
logger:
  color_eyre: false # 彩色日志
  console: # 终端配置
    level: "info" # 日志级别, debug/info/warn/error/panic
    enable: true # 是否启用，默认不启用
  console_bunyan: # bunyan 终端配置
    level: "debug" # 日志级别, trace/debug/info/warn/error
    enable: false # 是否启用，默认不启用
  file: # 文件配置
    filepath: "logs" # 日志路径
    filename: "app.log" # 日志文件名称
    level: "info" # 日志级别, trace/debug/info/warn/error
    enable: true # 是否启用，默认不启用
  db: # 数据库配置
    address: "mysql://one:pass@127.0.0.1:3306/axum_admin_web"
    # address: "sqlite://./data.dat?mode=rwc" # 数据库地址
    log_name: "logger" # 日志记录器名称
    level: "info" # 日志级别, trace/debug/info/warn/error
    enable: false # 是否启用，默认不启用
    options: # 参数配置
      max_connections: 5 # 设置池的最大连接数
      min_connections: 2 # 设置池的最小连接数
      connect_timeout: 10 # 设置获取连接时的超时持续时间
      acquire_timeout: 10 # 设置等待获取连接所花费的最大时间
      idle_timeout: 10 # 在关闭连接之前设置空闲持续时间
      max_lifetime: 10 # 设置单个连接的最大使用寿命
      logging_enable: false # 启用日志记录
      logging_level: "error" # 日志记录级别（默认info）off/trace/debug/info/warn/error
