[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
thiserror = { workspace = true }
