[package]
name = "service_hub"
version = "0.1.0"
edition = "2024"

[dependencies]
user = { path = "./user" }
auth = { path = "./auth" }
system = { path = "./system" }
log = { path = "./log" }
debox = { path = "./debox" }
