[build]
# rustflags = ["-C", "opt-level=2"] # 设置优化级别为 2 而不是使用 -march=native
# https://developer.android.google.cn/ndk/guides/other_build_systems?hl=zh-cn
target = 'x86_64-unknown-linux-gnu'
# target = 'aarch64-linux-android'
# target = 'armv7-linux-androideabi'
# target = 'x86_64-linux-android'


[target.aarch64-linux-android]
linker = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
ar = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

[target.armv7-linux-androideabi]
linker = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang"
ar = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

[target.x86_64-linux-android]
linker = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang"
ar = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

[target.i686-linux-android]
linker = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android35-clang"
ar = "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"


[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))']
rustflags = [
    "-C",
    # https://github.com/huggingface/candle/issues/1625
    "target-feature=+fp16",
]

[net]
git-fetch-with-cli = true # 强制 Cargo 使用 Git CLI 而不是内置的 Git 实现，可能会解决认证问题。
