[workspace]
resolver = "2"
members = [
    # 核心组件
    # "crates/core/code",

    # app 应用
    "mobile",
]

[workspace.dependencies]
tauri = "2.8"
tauri-plugin-opener = "2.5"
tauri-build = "2.4"
serde = "1.0"
serde_json = "1.0"
